"""Structured extraction prompts for multi-pass pipeline."""
from report_builder.prompts.extraction import (
    CONTENT_EXTRACTION_PROMPT,
    SEMANTIC_ANALYSIS_PROMPT,
    TABLE_EXTRACTION_PROMPT,
    CHART_DESCRIPTION_PROMPT,
    ENTITY_EXTRACTION_PROMPT,
)

__all__ = [
    "CONTENT_EXTRACTION_PROMPT",
    "SEMANTIC_ANALYSIS_PROMPT",
    "TABLE_EXTRACTION_PROMPT",
    "CHART_DESCRIPTION_PROMPT",
    "ENTITY_EXTRACTION_PROMPT",
]
