'use client';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { AlignCenter, AlignLeft, AlignRight, BarChart3, Bold, ChevronRight, Download, FileText, FunctionSquare, Hash, Image, Italic, Layers, Loader2, MessageSquare, Minus, Pause, Pencil, Play, Plus, Sparkles, Table2, TrendingUp, Type, Underline, Upload, X } from 'lucide-react';
import { generatePhaseApi } from '@/lib/api';

interface QueueItem { index: number; plan_id: string; question_id: string; component_type: string; title: string; section_path: string[]; status: string; }
interface GenBlock { index: number; kind: string; title: string; content: string; tableData?: Record<string, unknown>; metricValue?: string; metricUnit?: string; sectionPath: string[]; status: 'pending' | 'generating' | 'done' | 'error'; }
interface ChatMsg { id: string; role: 'user' | 'assistant'; content: string; ts: number; }
type Phase = 'init' | 'ready' | 'generating' | 'paused' | 'complete';
type Panel = 'left' | 'right' | null;
type LeftTab = 'pages' | 'elements' | 'upload';

function fmtNum(n: number | string | undefined | null): string {
  if (n == null || n === '') return '\u2014';
  const v = typeof n === 'string' ? parseFloat(n) : n;
  if (v == null || isNaN(v)) return String(n ?? '\u2014');
  if (Math.abs(v) >= 1e7) return (v / 1e7).toFixed(2) + ' Cr';
  if (Math.abs(v) >= 1e5) return (v / 1e5).toFixed(2) + ' L';
  if (Math.abs(v) >= 1000) return v.toLocaleString('en-IN', { maximumFractionDigits: 1 });
  return Number.isInteger(v) ? String(v) : v.toFixed(2);
}

export default function ReportCanvasPage() {
  const params = useParams();
  const templateId = params.templateId as string;
  const signature = params.signature as string;
  const [phase, setPhase] = useState<Phase>('init');
  const [queue, setQueue] = useState<QueueItem[]>([]);
  const [blocks, setBlocks] = useState<GenBlock[]>([]);
  const [selectedIdx, setSelectedIdx] = useState<number | null>(null);
  const [generating, setGenerating] = useState(false);
  const [panel, setPanel] = useState<Panel>(null);
  const [leftTab, setLeftTab] = useState<LeftTab>('pages');
  const [chatMsgs, setChatMsgs] = useState<ChatMsg[]>([]);
  const [chatInput, setChatInput] = useState('');
  const abortRef = useRef(false);
  const docRef = useRef<HTMLDivElement>(null);
  const togglePanel = (p: Panel) => setPanel(prev => prev === p ? null : p);

  useEffect(() => { generatePhaseApi.getGenerationQueue(templateId, signature).then(q => { setQueue(q || []); setBlocks((q || []).map(item => ({ index: item.index, kind: item.component_type === 'formula_metric' ? 'metric' : item.component_type, title: item.title, content: '', sectionPath: item.section_path || [], status: 'pending' as const }))); setPhase('ready'); }).catch(() => setPhase('ready')); }, [templateId, signature]);

  const generateOne = useCallback(async (idx: number) => { setBlocks(prev => prev.map(b => b.index === idx ? { ...b, status: 'generating' as const } : b)); try { const r = await generatePhaseApi.generateComponent(templateId, signature, { index: idx, use_llm: true, redo: false }); const c = r.content || {}; setBlocks(prev => prev.map(b => b.index === idx ? { ...b, content: r.narrative || String(c.text || c.content || c.value || ''), title: r.title || b.title, kind: r.component_type === 'formula_metric' ? 'metric' : r.component_type, tableData: (c.items || c.rankingData || c.rows) ? c as Record<string, unknown> : undefined, metricValue: c.value != null ? String(c.value) : undefined, metricUnit: c.unit ? String(c.unit) : undefined, status: 'done' as const } : b)); return true; } catch { setBlocks(prev => prev.map(b => b.index === idx ? { ...b, status: 'error' as const } : b)); return false; } }, [templateId, signature]);

  const autoGenerate = useCallback(async () => { setPhase('generating'); setGenerating(true); abortRef.current = false; for (const b of blocks) { if (abortRef.current) { setPhase('paused'); break; } if (b.status === 'done') continue; await generateOne(b.index); } setGenerating(false); if (!abortRef.current) { setPhase('complete'); generatePhaseApi.generate(templateId, signature, { use_llm: true, publish_mode: 'draft' }).catch(() => {}); } }, [blocks, generateOne, templateId, signature]);

  const sendChat = useCallback((msg: string) => { if (!msg.trim()) return; setChatMsgs(prev => [...prev, { id: `u-${Date.now()}`, role: 'user', content: msg, ts: Date.now() }]); setChatInput(''); setTimeout(() => { setChatMsgs(prev => [...prev, { id: `a-${Date.now()}`, role: 'assistant', content: `Processing: "${msg}". Select a block for context-aware actions.`, ts: Date.now() }]); }, 300); }, []);

  const doneCount = blocks.filter(b => b.status === 'done').length;
  const progress = blocks.length > 0 ? Math.round((doneCount / blocks.length) * 100) : 0;
  const selectedBlock = selectedIdx != null ? blocks.find(b => b.index === selectedIdx) : null;
  const sections = useMemo(() => { const m = new Map<string, GenBlock[]>(); blocks.forEach(b => { const k = (b.sectionPath || [])[b.sectionPath.length - 1] || 'Untitled'; if (!m.has(k)) m.set(k, []); m.get(k)!.push(b); }); return m; }, [blocks]);
  const reportTitle = templateId.replace(/^tpl_/, '').replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());

  return (<div className="flex h-screen flex-col overflow-hidden bg-[#f0f2f5]">
    <div className="flex h-11 items-center justify-between border-b border-slate-200 bg-white px-3 shrink-0">
      <div className="flex items-center gap-3"><button onClick={() => togglePanel('left')} className={`rounded p-1.5 ${panel === 'left' ? 'bg-blue-50 text-blue-600' : 'text-slate-500 hover:bg-slate-100'}`}><Layers className="h-4 w-4" /></button><Link href="/report-builder" className="text-slate-400 hover:text-slate-600"><ChevronRight className="h-3.5 w-3.5 rotate-180" /></Link><h1 className="text-[13px] font-semibold text-slate-800 truncate max-w-[200px]">{reportTitle}</h1></div>
      <div className="flex items-center gap-2">
        <div className="flex items-center gap-2 rounded-full bg-slate-100 px-3 py-1"><div className="h-1.5 w-14 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-emerald-500 transition-all duration-700" style={{ width: `${progress}%` }} /></div><span className="text-[10px] font-medium tabular-nums text-slate-600">{doneCount}/{blocks.length}</span></div>
        {phase === 'ready' && <button onClick={autoGenerate} className="flex items-center gap-1.5 rounded-md bg-blue-600 px-3 py-1.5 text-[11px] font-medium text-white hover:bg-blue-700"><Play className="h-3 w-3" /> Auto-Generate</button>}
        {phase === 'generating' && <button onClick={() => { abortRef.current = true; }} className="flex items-center gap-1.5 rounded-md bg-amber-500 px-3 py-1.5 text-[11px] font-medium text-white hover:bg-amber-600"><Pause className="h-3 w-3" /> Pause</button>}
        {phase === 'paused' && <button onClick={autoGenerate} className="flex items-center gap-1.5 rounded-md bg-blue-600 px-3 py-1.5 text-[11px] font-medium text-white hover:bg-blue-700"><Play className="h-3 w-3" /> Resume</button>}
        {phase === 'complete' && <a href={generatePhaseApi.reportPdfUrl(templateId, signature)} target="_blank" rel="noreferrer" className="flex items-center gap-1.5 rounded-md bg-emerald-600 px-3 py-1.5 text-[11px] font-medium text-white hover:bg-emerald-700"><Download className="h-3 w-3" /> PDF</a>}
        <button onClick={() => togglePanel('right')} className={`rounded p-1.5 ${panel === 'right' ? 'bg-blue-50 text-blue-600' : 'text-slate-500 hover:bg-slate-100'}`}><MessageSquare className="h-4 w-4" /></button>
      </div>
    </div>
    <div className="flex h-9 items-center gap-1 border-b border-slate-200 bg-white px-3 shrink-0">
      <div className="flex items-center gap-0.5 rounded border border-slate-200 px-1"><button className="rounded p-1 text-slate-500 hover:bg-slate-100"><Bold className="h-3 w-3" /></button><button className="rounded p-1 text-slate-500 hover:bg-slate-100"><Italic className="h-3 w-3" /></button><button className="rounded p-1 text-slate-500 hover:bg-slate-100"><Underline className="h-3 w-3" /></button></div>
      <span className="mx-1 h-4 w-px bg-slate-200" />
      <div className="flex items-center gap-0.5 rounded border border-slate-200 px-1"><button className="rounded p-1 text-slate-500 hover:bg-slate-100"><AlignLeft className="h-3 w-3" /></button><button className="rounded p-1 text-slate-500 hover:bg-slate-100"><AlignCenter className="h-3 w-3" /></button><button className="rounded p-1 text-slate-500 hover:bg-slate-100"><AlignRight className="h-3 w-3" /></button></div>
      <span className="mx-1 h-4 w-px bg-slate-200" />
      <div className="flex items-center gap-0.5 rounded border border-slate-200 px-1"><button className="rounded p-1 text-slate-500 hover:bg-slate-100" title="Chart"><BarChart3 className="h-3 w-3" /></button><button className="rounded p-1 text-slate-500 hover:bg-slate-100" title="Table"><Table2 className="h-3 w-3" /></button><button className="rounded p-1 text-slate-500 hover:bg-slate-100" title="Metric"><Hash className="h-3 w-3" /></button><button className="rounded p-1 text-slate-500 hover:bg-slate-100" title="Text"><Type className="h-3 w-3" /></button></div>
      <span className="mx-1 h-4 w-px bg-slate-200" />
      <select className="rounded border border-slate-200 bg-white px-2 py-0.5 text-[10px] text-slate-600"><option>A4</option><option>MoSPI</option><option>Letter</option></select>
      <select className="ml-1 rounded border border-slate-200 bg-white px-2 py-0.5 text-[10px] text-slate-600"><option>100%</option><option>75%</option><option>Fit</option></select>
    </div>
    <div className="flex flex-1 overflow-hidden">
      {panel === 'left' && (<div className="w-56 shrink-0 border-r border-slate-200 bg-white flex flex-col"><div className="flex border-b border-slate-100">{(['pages', 'elements', 'upload'] as const).map(tab => (<button key={tab} onClick={() => setLeftTab(tab)} className={`flex-1 py-2 text-[10px] font-semibold uppercase tracking-wide ${leftTab === tab ? 'border-b-2 border-blue-500 text-blue-600' : 'text-slate-400 hover:text-slate-600'}`}>{tab}</button>))}</div><div className="flex-1 overflow-auto p-2">{leftTab === 'pages' && (<div className="space-y-1">{Array.from(sections.entries()).map(([s, items]) => (<button key={s} onClick={() => { docRef.current?.querySelector(`[data-section="${s}"]`)?.scrollIntoView({ behavior: 'smooth' }); }} className="w-full rounded px-2 py-1.5 text-left text-[10px] font-medium text-slate-700 hover:bg-slate-50">{s} <span className="text-slate-400">({items.filter(i => i.status === 'done').length}/{items.length})</span></button>))}</div>)}{leftTab === 'elements' && (<div className="grid grid-cols-2 gap-1.5">{[{i: BarChart3, l: 'Chart'}, {i: Table2, l: 'Table'}, {i: Hash, l: 'Metric'}, {i: FileText, l: 'Text'}, {i: Image, l: 'Image'}, {i: Minus, l: 'Divider'}, {i: TrendingUp, l: 'Finding'}, {i: Pencil, l: 'Source'}, {i: Type, l: 'Heading'}, {i: Sparkles, l: 'AI Block'}].map(({i: Icon, l}) => (<button key={l} className="flex flex-col items-center gap-1 rounded-lg border border-slate-200 bg-slate-50 p-2.5 hover:border-blue-300 hover:bg-blue-50 active:scale-95 transition-all"><Icon className="h-4 w-4 text-slate-600" /><span className="text-[9px] font-medium text-slate-600">{l}</span></button>))}</div>)}{leftTab === 'upload' && (<div className="flex flex-col items-center rounded-lg border-2 border-dashed border-slate-200 bg-slate-50 p-6 text-center"><Upload className="h-6 w-6 text-slate-300" /><p className="mt-2 text-[10px] text-slate-500">Drop files here</p></div>)}</div></div>)}
      <div className="flex-1 overflow-auto p-6" onClick={() => setSelectedIdx(null)}>
        <div ref={docRef} className="mx-auto bg-white" style={{ width: '210mm', maxWidth: '100%', minHeight: '297mm', padding: '20mm 25mm', boxShadow: '0 1px 3px rgba(0,0,0,0.08), 0 4px 20px rgba(0,0,0,0.04)' }}>
          {Array.from(sections.entries()).map(([section, items]) => (<div key={section} data-section={section} className="mb-8"><h2 className="mb-3 mt-6 text-[16px] font-bold text-slate-900 first:mt-0">{section}</h2><div className="mb-4 h-px bg-slate-200" />{items.map(block => (<div key={block.index} onClick={e => { e.stopPropagation(); setSelectedIdx(block.index); }} className={`relative mb-4 rounded-sm transition-all cursor-pointer ${selectedIdx === block.index ? 'ring-2 ring-blue-400 ring-offset-1' : 'hover:ring-1 hover:ring-slate-200'}`}>
            {block.status === 'done' && (<div className="py-1">{(block.kind === 'narrative' || block.kind === 'key_finding') && <p className={`text-[12.5px] leading-[1.8] ${block.kind === 'key_finding' ? 'rounded bg-blue-50/60 px-4 py-3 font-medium' : ''} text-slate-700`}>{block.content}</p>}{block.kind === 'table' && block.tableData && (<div className="overflow-hidden rounded border border-slate-200"><div className="border-b border-slate-100 bg-slate-50 px-3 py-1.5"><span className="text-[10px] font-semibold text-slate-600">{block.title}</span></div><table className="w-full text-[10.5px]"><thead><tr className="border-b border-slate-100 bg-slate-50/50"><th className="px-3 py-1.5 text-left font-semibold text-slate-500">#</th><th className="px-3 py-1.5 text-left font-semibold text-slate-500">State/UT</th><th className="px-3 py-1.5 text-right font-semibold text-slate-500">{block.title}</th><th className="px-3 py-1.5 text-right font-semibold text-slate-500">Share</th></tr></thead><tbody>{((block.tableData.items || block.tableData.rankingData || []) as Array<{rank?: number; key?: Record<string, string>; value?: number}>).slice(0, 10).map((item, i) => { const total = ((block.tableData!.items || block.tableData!.rankingData || []) as Array<{value?: number}>).reduce((s, x) => s + (x.value || 0), 0); const pct = total > 0 && item.value ? ((item.value / total) * 100).toFixed(1) : '\u2014'; return (<tr key={i} className="border-b border-slate-100 last:border-b-0 hover:bg-blue-50/30"><td className="px-3 py-1 tabular-nums text-slate-400">{item.rank ?? i + 1}</td><td className="px-3 py-1 text-slate-700">{item.key ? Object.values(item.key)[0] : '\u2014'}</td><td className="px-3 py-1 text-right tabular-nums font-medium text-slate-800">{fmtNum(item.value)}</td><td className="px-3 py-1 text-right tabular-nums text-slate-400">{pct}%</td></tr>); })}</tbody></table></div>)}{block.kind === 'table' && !block.tableData && <p className="text-[12.5px] leading-[1.8] text-slate-700">{block.content}</p>}{block.kind === 'metric' && (<div className="flex items-baseline gap-2 rounded border border-slate-200 bg-gradient-to-r from-white to-slate-50 px-4 py-3"><span className="text-[24px] font-bold tabular-nums text-slate-800">{fmtNum(block.metricValue)}</span>{block.metricUnit && <span className="text-[11px] text-slate-400">{block.metricUnit}</span>}{block.content && <span className="ml-3 text-[11px] text-slate-500">{block.content}</span>}</div>)}{block.kind === 'source_note' && <p className="text-[9.5px] text-slate-400">Source: {block.content}</p>}{block.kind === 'chart' && (<div className="rounded border border-slate-200 p-4"><div className="flex h-32 items-end gap-[3%]">{[55, 80, 45, 70, 48, 85, 38, 62, 72, 50].map((h, i) => (<div key={i} className="flex-1 rounded-t" style={{ height: `${h}%`, background: `hsl(${215 + i * 3}, 50%, ${62 + i}%)` }} />))}</div><p className="mt-2 text-center text-[9px] text-slate-400">{block.title}</p></div>)}</div>)}
            {block.status === 'generating' && (<div className="py-2"><div className="mb-2 flex items-center gap-2"><Loader2 className="h-3 w-3 animate-spin text-blue-500" /><span className="text-[10px] font-medium text-blue-600">{block.title}</span></div><div className="space-y-1.5"><div className="h-2.5 w-full animate-pulse rounded bg-slate-100" /><div className="h-2.5 w-[90%] animate-pulse rounded bg-slate-100" /><div className="h-2.5 w-[75%] animate-pulse rounded bg-slate-100" /></div></div>)}
            {block.status === 'pending' && (<div className="flex items-center justify-between rounded border border-dashed border-slate-300 bg-slate-50/50 px-4 py-3" onClick={e => { e.stopPropagation(); generateOne(block.index); }}><div className="flex items-center gap-2"><span className="flex h-5 w-5 items-center justify-center rounded bg-slate-200 text-[9px] font-bold text-slate-500">{block.kind === 'table' ? '\u229e' : block.kind === 'chart' ? '\u25d1' : block.kind === 'metric' ? '#' : '\u00b6'}</span><span className="text-[11px] text-slate-500">{block.title}</span></div><span className="rounded bg-blue-100 px-2 py-0.5 text-[9px] font-medium text-blue-700 hover:bg-blue-200 cursor-pointer">Generate</span></div>)}
            {block.status === 'error' && (<div className="flex items-center gap-2 rounded border border-red-200 bg-red-50 px-4 py-2" onClick={e => { e.stopPropagation(); generateOne(block.index); }}><span className="text-[10px] text-red-600">Failed: {block.title}</span><span className="rounded bg-red-100 px-2 py-0.5 text-[9px] font-medium text-red-700 cursor-pointer hover:bg-red-200">Retry</span></div>)}
          </div>))}</div>))}
          {blocks.length === 0 && phase !== 'init' && <div className="flex h-60 flex-col items-center justify-center text-slate-400"><FileText className="h-8 w-8 text-slate-200" /><p className="mt-3 text-sm">No components loaded</p></div>}
          {phase === 'init' && <div className="flex h-60 items-center justify-center"><Loader2 className="h-5 w-5 animate-spin text-slate-300" /></div>}
        </div>
      </div>
      {panel === 'right' && (<div className="w-80 shrink-0 border-l border-slate-200 bg-white flex flex-col"><div className="flex items-center justify-between border-b border-slate-100 px-3 py-2"><div className="flex items-center gap-2"><div className="flex h-5 w-5 items-center justify-center rounded bg-gradient-to-br from-blue-500 to-indigo-600"><Sparkles className="h-2.5 w-2.5 text-white" /></div><span className="text-[11px] font-semibold text-slate-700">Deep BI Agent</span></div><button onClick={() => setPanel(null)} className="rounded p-1 text-slate-400 hover:bg-slate-100"><X className="h-3.5 w-3.5" /></button></div>{selectedBlock && selectedBlock.status === 'done' && (<div className="border-b border-slate-100 bg-slate-50/50 p-3"><p className="text-[9px] font-bold uppercase tracking-wide text-slate-400">Selected: {selectedBlock.kind}</p><p className="mt-1 truncate text-[11px] font-medium text-slate-700">{selectedBlock.title}</p><div className="mt-2 flex flex-wrap gap-1"><button onClick={() => generateOne(selectedBlock.index)} className="rounded bg-white border border-slate-200 px-2 py-0.5 text-[9px] font-medium text-slate-600 hover:bg-slate-50">Regenerate</button>{selectedBlock.kind === 'table' && <button className="rounded bg-white border border-slate-200 px-2 py-0.5 text-[9px] font-medium text-slate-600 hover:bg-slate-50">Top 5</button>}{selectedBlock.kind === 'narrative' && <button className="rounded bg-white border border-slate-200 px-2 py-0.5 text-[9px] font-medium text-slate-600 hover:bg-slate-50">Shorter</button>}<button className="rounded bg-white border border-slate-200 px-2 py-0.5 text-[9px] font-medium text-slate-600 hover:bg-slate-50">Explain</button></div></div>)}<div className="flex-1 overflow-auto p-3 space-y-2">{chatMsgs.map(m => (<div key={m.id} className={m.role === 'user' ? 'ml-8' : ''}><div className={`rounded-lg px-3 py-2 text-[11px] leading-relaxed ${m.role === 'user' ? 'bg-blue-600 text-white' : 'bg-slate-100 text-slate-700'}`}>{m.content}</div></div>))}{chatMsgs.length === 0 && <div className="py-8 text-center text-[10px] text-slate-400"><p>Select a block, then ask questions</p><p>or request modifications.</p></div>}</div><form onSubmit={e => { e.preventDefault(); sendChat(chatInput); }} className="border-t border-slate-100 p-2"><div className="flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-1.5 focus-within:border-blue-300 focus-within:ring-1 focus-within:ring-blue-200"><input value={chatInput} onChange={e => setChatInput(e.target.value)} placeholder="Ask about the selected block..." className="flex-1 bg-transparent text-[11px] text-slate-700 placeholder:text-slate-400 outline-none" /><button type="submit" disabled={!chatInput.trim()} className="rounded bg-blue-600 px-2 py-0.5 text-[9px] font-medium text-white disabled:opacity-30">Send</button></div></form></div>)}
    </div>
  </div>);
}